src/habrhub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("parsing.urls"))
]

src/parsing/urls.py
from django.urls import path

from .views import HubsIndexView


app_name = "parsing"
urlpatterns = [
    path('', HubsIndexView.as_view(), name='hubs_index'),
]

src/parsing/models.py
from django.db import models
from django_celery_beat.models import PeriodicTask
from django.dispatch import receiver


class Hub(models.Model):
    title = models.CharField(max_length=150)
    url = models.URLField(unique=True)
    parse_task = models.OneToOneField(PeriodicTask, on_delete=models.CASCADE, blank=True, null=True)
    
    def __str__(self) -> str:
        return f"{self.title}(#{self.id})"

@receiver(models.signals.post_delete, sender=Hub)
def delete_hub_parse_task(sender, instance: Hub, **kwargs):
    try:
        parse_task = instance.parse_task
    except PeriodicTask.DoesNotExist:
        return

    if parse_task is not None:
        parse_task.delete()

class ArticleAuthor(models.Model):
    username = models.CharField(max_length=150)
    url = models.URLField(unique=True)

    def __str__(self) -> str:
        return f"{self.username}(#{self.id})"

class Article(models.Model):
    title = models.CharField(max_length=250)
    text = models.TextField()
    url = models.URLField(unique=True)
    author = models.ForeignKey(ArticleAuthor, on_delete=models.CASCADE)
    hub = models.ForeignKey(Hub, on_delete=models.CASCADE)
    published_at = models.DateTimeField()

    def __str__(self) -> str:
        return f"{self.title}(#{self.id})"

src/parsing/forms.py
import json
from datetime import datetime, timezone

from django import forms
from django.db.transaction import atomic
from django_celery_beat.models import IntervalSchedule
from django.contrib.admin.widgets import RelatedFieldWidgetWrapper
from django_celery_beat.models import PeriodicTask
from django.contrib import admin

from .models import Hub


class HubCreationForm(forms.ModelForm):
    interval = forms.ModelChoiceField(IntervalSchedule.objects.all(), label="Parsing period")
    task_enabled = forms.BooleanField(label="Parsing enabled", initial=True, required=False)

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        rel = PeriodicTask._meta.get_field("interval").remote_field
        self.fields["interval"].widget = RelatedFieldWidgetWrapper(self.fields["interval"].widget, rel, admin.site, can_add_related=True, can_change_related=True)

    class Meta:
        model = Hub
        exclude = ("parse_task",)

    @atomic
    def save(self, commit: bool = True) -> Hub:
        super().save(commit=False)

        hub = Hub(
            title=self.cleaned_data.get("title"),
            url=self.cleaned_data.get("url")
        )
        hub.save()
        
        task = PeriodicTask.objects.create(
            name=f"Parse {self.cleaned_data.get('url')}",
            task="parsing.tasks.parse_hub_task",
            interval=self.cleaned_data.get("interval"),
            enabled=self.cleaned_data.get("task_enabled"),
            kwargs=json.dumps({"hub_id": hub.id}),
            start_time=datetime.now(tz=timezone.utc)
        )
        hub.parse_task = task

        if commit:
            hub.save()
        return hub

class HubUpdateForm(forms.ModelForm):
    interval = forms.ModelChoiceField(IntervalSchedule.objects.all(), label="Parsing period")
    task_enabled = forms.BooleanField(label="Parsing enabled", required=False)

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        rel = PeriodicTask._meta.get_field("interval").remote_field
        self.fields["interval"].widget = RelatedFieldWidgetWrapper(self.fields["interval"].widget, rel, admin.site, can_add_related=True, can_change_related=True)
        
        self.fields["interval"].initial = self.instance.parse_task.interval
        self.fields["task_enabled"].initial = self.instance.parse_task.enabled

    class Meta:
        model = Hub
        exclude = ("parse_task",)

    @atomic
    def save(self, commit: bool = True) -> Hub:
        super().save(commit=False)
        self.instance.parse_task.interval = self.cleaned_data.get("interval")
        self.instance.parse_task.enabled = self.cleaned_data.get("task_enabled")
        self.instance.parse_task.name = f"Parse {self.cleaned_data.get('url')}"
        self.instance.parse_task.save()
        
        self.instance.title = self.cleaned_data.get("title")
        self.instance.url = self.cleaned_data.get("url")

        if commit:
            self.instance.save()
        return self.instance

src/parsing/views.py
from django.views.generic import ListView
from django.db.models import QuerySet

from .models import Hub


class HubsIndexView(ListView):
    paginate_by = 10
    model = Hub
    template_name = "hubs_index.html"

    def get_queryset(self) -> QuerySet[Hub]:
        return self.model.objects.order_by("title")

src/parsing/templates/hubs_index.html
{% extends 'base.html' %}

{% block content %}
{% if page_obj|length == 0 %}
    <div class="d-flex flex-column align-items-center mb-3 fs-3">
        <span>We have no hubs registred right now! Come back later.</span>
        <i class="fa fa-face-surprise fs-1"></i>
    </div>
{% else %}
<ul class="w-100">
    {% for hub in page_obj %}
        <li class="card mt-4"></li>
        <div class="card-body row align-items-center">
            <div class="col-8">
                <h5 class="card-title position-relative">{{hub.title}}</h5>
                <h6 class="card-subtitle">
                    <a class="text-decoration-none" target="_blank" href="{{hub.url}}">{{hub.url}}</a>
                </h6>
            </div>
            <div class="col-4 d-flex flex-column">
                <span title="Parsing period">
                    <i class="fa fa-stopwatch"></i>
                    {{hub.parse_task.interval}}
                </span>
                {% if hub.parse_task.last_run_at %}
                    <span title="Last parsing">
                        <i  class="fa fa-clock"></i>
                        {{hub.parse_task.last_run_at|timesince}} ago
                    </span>
                {% endif %}
                {% if hub.parse_task.total_run_count > 0 %}
                    <span title="Times parsed">
                        <i class="fa fa-gears"></i>
                        {{hub.parse_task.total_run_count}}
                    </span>
                {% endif %}
                <span title="Articles parsed">
                    <i  class="fa fa-newspaper"></i>
                    {{hub.article_set.count}}
                </span>
            </div>
        </div>
    {% endfor %}
</ul>
{% if page_obj.has_previous or page_obj.has_next %}
    <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a href="?page={{page_obj.previous_page_number}}" class="page-link">
                <span class="fa fa-left-long"></span>
            </a></li>
            {% endif %}

            <li class="page-item active"><span class="page-link" style="cursor: pointer;">{{page_obj.number}}</span></li>

            {% if page_obj.has_next %}
            <li class="page-item"><a href="?page={{page_obj.next_page_number}}" class="page-link">
                <span class="fa fa-right-long"></span>
            </a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
{% endif %}
{% endblock %}

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome_solid.min.css' %}">
    <title>{% block title %}HabrHub{% endblock %}</title>
  </head>
  <body>
    <div class="container py-3 d-flex flex-column justify-content-center align-items-center">
        {% block content %}
        {% endblock %}
    </div>
  </body>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  {% block scripts %}
  {% endblock %}
</html>